language: python
install:
  - pip install awscli
script:
  - gzip cyclomedia-20-06-mapboard.js
  - mv cyclomedia-20-06-mapboard.js.gz cyclomedia-20-06-mapboard.js
  - aws s3 cp cyclomedia-20-06-mapboard.js s3://cyclomedia-mapboard --content-encoding gzip
  - aws s3 cp helvetiker_regular.typeface.json s3://cyclomedia-mapboard
  - aws s3 cp loading-mini.gif s3://cyclomedia-mapboard
